AppBundle\Entity\Department:
    type: entity
    table: department
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        name:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
    manyToMany:
        stuff:
            targetEntity: Stuff
            cascade: {  }
            fetch: LAZY
            mappedBy: department
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
