AppBundle\Entity\Stuff:
    type: entity
    table: stuff
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        firstName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: last_name
        middleName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: middle_name
        sex:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        salary:
            type: bigint
            nullable: true
            options:
                unsigned: false
    manyToMany:
        department:
            targetEntity: Department
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: stuff
            joinTable:
                name: stuff_department
                joinColumns:
                    -
                        name: stuff_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: department_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
